before_script:
    - service postgresql start && service redis-server start
    - virtualenv nanohttp-ve
    - source nanohttp-ve/bin/activate
    - pip install -e . -r requirements-ci.txt

stages:
    - test coverage
    - wiki

test and coverage:
    stage: test coverage
    script:
        - pytest --cov=nanohttp
    artifacts:
        name: $CI_PROJECT_TITLE-$CI_COMMIT_REF_SLUG
        paths:
            - data/markdown
        when: on_success
        expire_in: 2h

